services:
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: etoile-frontend
        working_dir: /workspace
        volumes:
            - ./frontend:/workspace
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        restart: unless-stopped
        stdin_open: true
        tty: true
        networks:
            main:  
                ipv4_address: 192.168.0.2
    
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: etoile-backend
        working_dir: /workspace
        volumes:
            - ./backend:/workspace
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - postgres_db
        restart: unless-stopped
        stdin_open: true
        tty: true
        networks:
            main:  
                ipv4_address: 192.168.0.3

    postgres_db:
        image: postgres:15
        container_name: etoile_database
        restart: always
        environment:
            POSTGRES_USER: etoile_admin
            POSTGRES_PASSWORD: supertajnehaslo123
            POSTGRES_DB: etoile_db
        ports:
            - "5400:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
        networks:
            main:  
                ipv4_address: 192.168.0.4
volumes:
    pgdata:
networks:
    main:
        ipam:
            config:
                - subnet: 192.168.0.0/24
